/** Server-safe registry keys — no dynamic imports (those live in IndustryModuleLoader). */
const MODULE_KEYS = new Set([
  "technology/seo",
  "technology/aio",
  "technology/website-design-development",
  "technology/business-automation",
  "technology/viral-social-media",
  "home-services/google-business-profile",
  "home-services/business-automation",
  "home-services/review-reputation-growth",
  "home-services/seo",
  "home-services/website-design-development",
  "transportation-logistics/seo",
  "transportation-logistics/custom-software",
  "transportation-logistics/business-automation",
  "transportation-logistics/paid-ads-management",
  "transportation-logistics/mobile-app-development",
  "construction/website-design-development",
  "construction/custom-software",
  "construction/seo",
  "construction/mobile-app-development",
  "construction/review-reputation-growth",
  "retail-ecommerce/website-design-development",
  "retail-ecommerce/seo",
  "retail-ecommerce/business-automation",
  "retail-ecommerce/paid-ads-management",
  "retail-ecommerce/viral-social-media",
  "healthcare/review-reputation-growth",
  "healthcare/seo",
  "healthcare/business-automation",
  "healthcare/website-design-development",
  "healthcare/paid-ads-management",
  "manufacturing/seo",
  "manufacturing/website-design-development",
  "manufacturing/custom-software",
  "manufacturing/business-automation",
  "manufacturing/paid-ads-management",
  "restaurants-hospitality/google-business-profile",
  "restaurants-hospitality/review-reputation-growth",
  "restaurants-hospitality/viral-social-media",
  "restaurants-hospitality/business-automation",
  "restaurants-hospitality/mobile-app-development",
  "professional-services/seo",
  "professional-services/website-design-development",
  "professional-services/business-automation",
  "professional-services/aio",
  "professional-services/review-reputation-growth",
  "startups/website-design-development",
  "startups/business-automation",
  "startups/seo",
  "startups/aio",
  "startups/viral-social-media",
]);

export function hasIndustryServiceModules(
  industrySlug: string,
  serviceSlug: string,
): boolean {
  return MODULE_KEYS.has(`${industrySlug}/${serviceSlug}`);
}
